services:
  # приложение Next.js
  web:
    # сборка на основе Dockerfile
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://rizo9235_rach3000:qwerty228337!@37.27.63.3:3306/rizo9235_kvf_tasks
      - NODE_ENV=development
      - NEXTAUTH_SECRET=Ov23lilHvIs9YfXbr8Am
      - NEXTAUTH_URL=https://24kvf.ru/
      - AWS_ACCESS_KEY_ID=YCAJEghK7d7vCQo-xeDtKbHvF
      - AWS_SECRET_ACCESS_KEY=YCP2IvTts-544L6P9gyqoHqst28H27Iy3gYD_Uew
      - EMAIL_SERVER_USER=ladamelikovna@gmail.com
      - EMAIL_SERVER_PASSWORD=2CcIELFtiQKj
      - EMAIL_SERVER_HOST=connect.smtp.bz
      - EMAIL_SERVER_PORT=465
      - EMAIL_FROM=noreply@24kvf.ru
    networks:
      - my_network
    # приложение зависит от БД

networks:
  my_network:
    driver: bridge
